NAME = libft.a

CC = cc

CFLAGS = -Werror -Wall -Wextra

SRCS = ft_strcmp.c ft_itoa.c ft_putstr_fd.c ft_strmapi.c ft_atoi.c ft_memchr.c ft_split.c ft_strncmp.c \
ft_bzero.c ft_memcmp.c ft_strchr.c ft_strnstr.c ft_calloc.c ft_memcpy.c ft_strdup.c ft_strrchr.c \
ft_isalnum.c ft_memmove.c ft_striteri.c ft_strtrim.c ft_isalpha.c ft_memset.c ft_strjoin.c \
ft_substr.c ft_isascii.c ft_putchar_fd.c ft_strlcat.c ft_tolower.c ft_isdigit.c ft_putendl_fd.c \
ft_strlcpy.c ft_toupper.c ft_isprint.c ft_putnbr_fd.c ft_strlen.c \
./ft_printf/ft_putchar.c ./ft_printf/ft_putstr.c ./ft_printf/ft_puthex.c \
./ft_printf/ft_putchex.c ./ft_printf/ft_putnbr.c ./ft_printf/ft_putptr.c \
./ft_printf/ft_unsigned.c ./ft_printf/ft_spf.c ./ft_printf/ft_printf.c \
./gnl/get_next_line.c ./gnl/get_next_line_utils.c

OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
		ar -rcs $(NAME) $?

.PHONY: all clean fclean re

clean:
		rm -rf $(OBJS)

fclean: clean
		rm -rf $(NAME)

re: fclean all